version: "3.3"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - "8080:80"

  api:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./src/api/:/var/www/html"
    ports:
      - "5000:80"

  frontend:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./frontend/:/var/www/html"
    ports:
      - "8000:80"
