<form method="POST" action="../webhook/create"  >
<table class="">
    <tr><td>WebHook Name :</td><td><input type="text" name="hookname" ></td></tr>
    <tr><td>Event :</td><td><input type="text" name="event" ></td></tr>
    <tr><td>Key :</td><td><input type="text" name="key" ></td></tr>
    <tr><td>URL :</td><td><input type="text"  name="url" ></td></tr>
    <tr><td><button class="btn btn-primary">Send</button><td></tr>
</table>
</form>
