<table><tr>
    
    <td><form action="../product/search" method="POST"><input onchange="this.form.submit()" type="text" placeholder="Search Product Name" name="search" ></form></td>
</tr></table>

  
<?php  ?>
    <table class="table">
        <thead><tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Stock</th></tr></thead>
   <?php foreach($result as $v){?>
    <tbody>
   <tr>
    
    <td><?php echo $v['name']; ?></td>
   <td><?php echo $v['category']; ?></td>
   <td><?php echo $v['price']; ?></td>
   <td><?php echo $v['stock']; ?></td>
   <td><form  action="../order/neworder" method="POST" ><button class="btn btn-warning" name="newOrder" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" >Order Now</button></form></td>

   <td><form action="../product/edit" method="POST"><button  class="btn btn-primary" name="view" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" data-toggle="modal" data-target="#exampleModalCenter">
    Quick View
    </button></form>
    <!-- <button type="button" class="btn btn-success editbtn"> EDIT </button> -->
</td>
   </tr>

   <?php }?>
    </tbody>
    </table>
 
