<table><tr>
    <td><a class="btn btn-primary" href="order" >Orders</a></td>
    <td><a class="btn btn-success" href="product" >Add Product</a></td>
    
    <td><form action="../product/search" method="POST"><input onchange="this.form.submit()" type="text" placeholder="Search Product Name" name="search" ></form></td>
    <td></td><td><a href="../login/logout" class="btn-danger btn" >LogOut</a></td>
</tr></table>

  
<?php  ?>
    <table class="table">
        <thead><tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Stock</th></tr></thead>
   <?php foreach($result as $v){?>
    <tbody>
   <tr>
    
    <td><?php echo $v['name']; ?></td>
   <td><?php echo $v['category']; ?></td>
   <td><?php echo $v['price']; ?></td>
   <td><?php echo $v['stock']; ?></td>
   <td><form  action="../order/neworder" method="POST" ><button class="btn btn-warning" name="newOrder" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" >Order Now</button></form></td>

   <td><form action="../product/edit" method="POST"><button  class="btn btn-primary" name="view" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" data-toggle="modal" data-target="#exampleModalCenter">
    Quick View
    </button></form>
    <!-- <button type="button" class="btn btn-success editbtn"> EDIT </button> -->
</td>
   <td><form  action="../product/delete" method="POST" ><button class="btn btn-danger" name="delete" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" >Delete</button></form></td></tr>

   <?php }?>
    </tbody>
    </table>
 


<script>
        $(document).ready(function () {

            $('.editbtn').on('click', function () {
               console.log("hello");
                $('#editmodal').modal('show');

                $tr = $(this).closest('tr');

                var data = $tr.children("td").map(function () {
                    return $(this).text();
                }).get();

                console.log(data);

                $('#update_id').val(data[0]);
                $('#fname').val(data[1]);
                $('#lname').val(data[2]);
                $('#course').val(data[3]);
                $('#contact').val(data[4]);
            });
        });
    </script>
