<?php if($flag == 1){ ?>
    <table class="table">
        <thead><tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Stock</th></tr></thead>
   <?php foreach($result as $v){
    ?>
    <tbody>
   <tr><td><?php echo $v['name']; ?></td>
   <td><?php echo $v['category']; ?></td>
   <td><?php echo $v['price']; ?></td>
   <td><?php echo $v['stock']; ?></td>
   <td><form  action="../order/neworder" method="POST" ><button class="btn btn-warning" name="newOrder" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>" >Order Now</button></form></td>
   <td><form action="../product/edit" method="POST"><button class="btn btn-warning" name="view" value="<?php foreach($v['_id'] as $k ){
               echo ($k);
           } ?>">Quick View</button></form></td>

   <?php }?>
    </tbody>
    </table>
 <?php 
}
